plot_detection_prevalence_heatmap_wc: '{fs_prefix}/{df}/feature_tables/{sample_set}/{ft_name}/{filter_chain}/detection_prevalence_heatmap_{heatmap_preset}.pdf'
plot_detection_prevalence_heatmap_source_wc: '{fs_prefix}/{df}/feature_tables/{sample_set}/{ft_name}/{filter_chain}/detection_prevalence_heatmap_{heatmap_preset}.pdf'
